
on: [push]
  
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install Flask
        
    - name: Build and publish
      run: |
        sudo apt install docker -y
        python main.py 
        docker build -t test .
        docker run -p 8080:8080 --name test_container test
